# B0 campaign env (pi0 + shadow original world). source this, then run campaign.py under env -i.
B0ENV=(HOME="$HOME" PATH="$PATH" USER="${USER:-}" LANG=C.UTF-8
  DEMO_ROUTER=0 DEMO_POLICY=canonical REPAIR_ABLATION=all
  CARRIER_RESCUE=1 DEMO_ANIM=0 ENERGY_OBJECTIVE=1 RESPEC_DEPRIO_KAPPA=0.25
  RESPEC_TRANSLATE_ON_INFEASIBLE=0 RESTAGE_NAV_BUFFER=0 RESTAGE_RING_STEP_FRAC=0.34
  RESTAGE_ZONE_MARGIN_FRAC=0.5 SPARE_PRIORITY=1 TEAM_PRIORITY=1 ZONE_CAUSAL_RULE=0
  ZONE_CHECK_PATHS=0 ZONE_DOMAIN_GATE=0 ZONE_RESCUE=1 ZONE_REPAIR_VERIFICATION=shadow)
